
# jekyll configuration
markdown: redcarpet
permalink: date
pygments: true
safe: true
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - README.md
    - reference

# Site variables
base_url: /

redcarpet:
    extensions:
        - fenced_code_blocks
        - superscript
