
# jekyll configuration
markdown: redcarpet
permalink: date
pygments: true
safe: true
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - lee-dohm.com-posts.sublime-project
  - lee-dohm.com-posts.sublime-workspace
  - lee-dohm.com.sublime-project
  - lee-dohm.com.sublime-workspace

redcarpet:
  extensions:
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - highlight
    - strikethrough
    - superscript
    - tables

# Site variables
base_url: /
full_url: http://www.lee-dohm.com
feed_url: feed.xml

title: lee-dohm.com

author:
  name: Lee Dohm
  email: lee@liftedstudios.com
  github: lee-dohm
